services:
  # Configuration du Static Site pour le frontend Angular
  - type: static
    name: stock-management-frontend
    buildCommand: npm run build
    staticPublishPath: dist/stock-management-frontend
    envVars:
      - key: NODE_VERSION
        value: 20
